const fs = require('fs');
const file = 'components/sections/DecisionIntelligenceDashboard.jsx';
let code = fs.readFileSync(file, 'utf8');

// 1. Remove the static import
code = code.replace("import { calculateDecisionAnalytics } from '@/lib/decisionEngine';", "");

// 2. Add dynamic fetching inside the component
const oldComponentStart = "export default function DecisionIntelligenceDashboard({ project }) {";
const newComponentStart = `export default function DecisionIntelligenceDashboard({ project }) {
  const [isMounted, setIsMounted] = useState(false);
  const [analytics, setAnalytics] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setIsMounted(true);
    
    // Fetch dynamic insights
    async function fetchAnalytics() {
      try {
        const res = await fetch(\`/api/projects/\${project._id}/decision-intelligence\`);
        const data = await res.json();
        if (res.ok) setAnalytics(data);
      } catch (err) {
        console.error('Failed to fetch analytics', err);
      } finally {
        setLoading(false);
      }
    }
    
    if (project?._id) {
      fetchAnalytics();
    }
  }, [project]);

  if (!isMounted) return null;

  if (loading) {
    return (
      <div className="w-full h-96 flex flex-col items-center justify-center space-y-4">
        <div className="w-12 h-12 border-4 border-[#2563EB]/20 border-t-[#2563EB] rounded-full animate-spin" />
        <p className="text-sm font-medium text-[#64748B] animate-pulse">Synthesizing Executive Insights with Gemini 3.5...</p>
      </div>
    );
  }

  if (!analytics) return null;
`;

// Remove the old state logic
const oldStateLogic = `  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const analytics = calculateDecisionAnalytics(project);

  if (!analytics) return null;`;

code = code.replace(oldStateLogic, newComponentStart);
code = code.replace("export default function DecisionIntelligenceDashboard({ project }) {\n" + newComponentStart, newComponentStart); 

// Add the infographic below the Executive Summary
const oldExeEnd = `      </Card>

      {/* KPI Cards */}`;

const newExeEnd = `      </Card>

      {/* Dynamic Infographic generated by Nano Banana 2 */}
      {analytics.infographic && (
        <FadeIn delay={0.2}>
          <Card className="overflow-hidden border border-white/10 relative group">
            <div className="absolute top-4 left-4 z-10">
              <Badge className="bg-[#1E293B]/80 backdrop-blur-md text-white border-white/20">
                <Lightbulb className="w-3 h-3 mr-1 inline" />
                AI Generated Infographic
              </Badge>
            </div>
            <img 
              src={analytics.infographic} 
              alt="Decision Intelligence Infographic" 
              className="w-full h-auto object-cover rounded-xl shadow-lg transition-transform duration-700 group-hover:scale-105"
            />
          </Card>
        </FadeIn>
      )}

      {/* KPI Cards */}`;

code = code.replace(oldExeEnd, newExeEnd);

fs.writeFileSync(file, code);
console.log('Patched dashboard!');
